version: "3.8"

services:
  backend:
    image: django-image:latest
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - mynetwork
    environment:
      - DB_ENGINE=django.db.backends.mysql
      - DB_NAME=django_testing
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_HOST=mysql
      - DB_PORT=3306
    restart: always

  mysql:
    image: mysql:latest
    networks:
      - mynetwork
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=django_testing
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    networks:
      - mynetwork
    ports:
      - "9090:80"  # Mapping host port 9090 to container port 80
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    restart: always

networks:
  mynetwork:
    name: django-network
    driver: bridge
